[[constraint]]
  name = "github.com/open-policy-agent/opa"
  version = "0.10.1"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/errors"

[[constraint]]
  branch = "master"
  name = "github.com/tv42/httpunix"

[prune]
  go-tests = true
  unused-packages = true
